### ISSUE TITLE
Payment security issue

### ISSUE THREAD

**Issue by nosuchip** [bluedisk/django-iamport#1]
In example here user can set any amount to pay and it will be used when sending request to iamport and code does not validate it. In other words, use can pay any amount instead of desired one and it will be processed as correct payment.

https://github.com/bluedisk/django-iamport/blob/master/payment/templates/payment/summary.html#L17

**Comment by bluedisk** [comment]
Thank you for your post.
I must admit that the processes are not look so safe and need to make more protections - ex: notifiction check, signing or something -, but it has some protections now.

To prevent changing amount attack, pay view call the 'prepare' REST API that is not documented well.
the amount of payment will be pegged by prepare call with 'merchant_uid' that is a unique key for each payment event.

You can show the code at [https://github.com/bluedisk/django-iamport/blob/e12699e8d368d243f14870776ff9f1cfb86a91cb/payment/views.py#L41-L45](https://github.com/bluedisk/django-iamport/blob/e12699e8d368d243f14870776ff9f1cfb86a91cb/payment/views.py#L41-L45)

If someone changes the amount of payment in js or browser console after pegged by prepare call, iamport will deny processing.
I want to share the document for this, but I can't find the official document... and I swear that I've seen this before!
the only place to see that information is 3rd party iamport rest module for python, following
[https://github.com/iamport/iamport-rest-client-python](https://github.com/iamport/iamport-rest-client-python)

And another protection to prevent changing amount is checking amount at updating result.
If amount that was returned by result is not matched with amount that has saved in server, whole transaction will be canceled.
that code is following
[https://github.com/bluedisk/django-iamport/blob/e12699e8d368d243f14870776ff9f1cfb86a91cb/payment/views.py#L71-L75](https://github.com/bluedisk/django-iamport/blob/e12699e8d368d243f14870776ff9f1cfb86a91cb/payment/views.py#L71-L75)

if you find some problems on this processes, please don't hesitate to reopen new issue.
again, thank you for your attention!
